use role_test;
set foreign_key_checks=0;
truncate orders;
truncate persons;
set foreign_key_checks=1;
insert into persons (person_name) values ('name_28409'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_17062', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16767', @person_id); 
insert into persons (person_name) values ('name_3928'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_219', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15189', @person_id); 
insert into orders (order_detail, person_id) values ('detail_32653', @person_id); 
insert into persons (person_name) values ('name_8159'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_4324', @person_id); 
insert into orders (order_detail, person_id) values ('detail_31698', @person_id); 
insert into orders (order_detail, person_id) values ('detail_6215', @person_id); 
insert into persons (person_name) values ('name_29563'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_5900', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15564', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11252', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24270', @person_id); 
insert into persons (person_name) values ('name_12083'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19814', @person_id); 
insert into persons (person_name) values ('name_5837'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_11134', @person_id); 
insert into orders (order_detail, person_id) values ('detail_2644', @person_id); 
insert into orders (order_detail, person_id) values ('detail_6489', @person_id); 
insert into orders (order_detail, person_id) values ('detail_19289', @person_id); 
insert into persons (person_name) values ('name_26332'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_8380', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12874', @person_id); 
insert into orders (order_detail, person_id) values ('detail_22655', @person_id); 
insert into persons (person_name) values ('name_9402'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19754', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4502', @person_id); 
insert into orders (order_detail, person_id) values ('detail_10530', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12659', @person_id); 
insert into orders (order_detail, person_id) values ('detail_1717', @person_id); 
insert into persons (person_name) values ('name_31393'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_4384', @person_id); 
insert into orders (order_detail, person_id) values ('detail_917', @person_id); 
insert into persons (person_name) values ('name_14602'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19322', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24762', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28415', @person_id); 
insert into persons (person_name) values ('name_12730'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_16672', @person_id); 
insert into orders (order_detail, person_id) values ('detail_10200', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26167', @person_id); 
insert into persons (person_name) values ('name_25036'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_18162', @person_id); 
insert into orders (order_detail, person_id) values ('detail_21843', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16173', @person_id); 
insert into persons (person_name) values ('name_16759'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_29604', @person_id); 
insert into orders (order_detail, person_id) values ('detail_13695', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11896', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20115', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16323', @person_id); 
insert into persons (person_name) values ('name_17275'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_26918', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28182', @person_id); 
insert into orders (order_detail, person_id) values ('detail_47', @person_id); 
insert into persons (person_name) values ('name_6110'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_28877', @person_id); 
insert into orders (order_detail, person_id) values ('detail_10853', @person_id); 
insert into orders (order_detail, person_id) values ('detail_21408', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24507', @person_id); 
insert into persons (person_name) values ('name_10132'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_26670', @person_id); 
insert into orders (order_detail, person_id) values ('detail_17810', @person_id); 
insert into persons (person_name) values ('name_13328'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_11683', @person_id); 
insert into orders (order_detail, person_id) values ('detail_13142', @person_id); 
insert into orders (order_detail, person_id) values ('detail_29681', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24550', @person_id); 
insert into persons (person_name) values ('name_4904'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_18339', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15742', @person_id); 
insert into orders (order_detail, person_id) values ('detail_22577', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8884', @person_id); 
insert into persons (person_name) values ('name_23987'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_13647', @person_id); 
insert into orders (order_detail, person_id) values ('detail_1528', @person_id); 
insert into persons (person_name) values ('name_6728'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_3886', @person_id); 
insert into orders (order_detail, person_id) values ('detail_9229', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4503', @person_id); 
insert into persons (person_name) values ('name_27143'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_8936', @person_id); 
insert into orders (order_detail, person_id) values ('detail_13421', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28015', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8607', @person_id); 
insert into orders (order_detail, person_id) values ('detail_32280', @person_id); 
insert into persons (person_name) values ('name_31090'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_25138', @person_id); 
insert into orders (order_detail, person_id) values ('detail_29411', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11084', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8833', @person_id); 
insert into persons (person_name) values ('name_25623'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_13613', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11315', @person_id); 
insert into orders (order_detail, person_id) values ('detail_31303', @person_id); 
insert into persons (person_name) values ('name_101'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_1721', @person_id); 
insert into orders (order_detail, person_id) values ('detail_5714', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26014', @person_id); 
insert into persons (person_name) values ('name_28729'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_24310', @person_id); 
insert into orders (order_detail, person_id) values ('detail_27472', @person_id); 
insert into orders (order_detail, person_id) values ('detail_27944', @person_id); 
insert into orders (order_detail, person_id) values ('detail_30953', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18425', @person_id); 
insert into persons (person_name) values ('name_19926'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_22026', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14740', @person_id); 
insert into persons (person_name) values ('name_11959'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_1483', @person_id); 
insert into orders (order_detail, person_id) values ('detail_2344', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15219', @person_id); 
insert into persons (person_name) values ('name_4361'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_9921', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28579', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20674', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8634', @person_id); 
insert into persons (person_name) values ('name_18788'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_31496', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26779', @person_id); 
insert into persons (person_name) values ('name_19497'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_11145', @person_id); 
insert into orders (order_detail, person_id) values ('detail_23338', @person_id); 
insert into orders (order_detail, person_id) values ('detail_13020', @person_id); 
insert into orders (order_detail, person_id) values ('detail_6511', @person_id); 
insert into persons (person_name) values ('name_20771'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_23472', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14616', @person_id); 
insert into orders (order_detail, person_id) values ('detail_2241', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16506', @person_id); 
insert into persons (person_name) values ('name_14592'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_26965', @person_id); 
insert into orders (order_detail, person_id) values ('detail_22700', @person_id); 
insert into persons (person_name) values ('name_3656'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_21164', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20687', @person_id); 
insert into orders (order_detail, person_id) values ('detail_30620', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18658', @person_id); 
insert into persons (person_name) values ('name_828'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_29125', @person_id); 
insert into persons (person_name) values ('name_30734'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_26238', @person_id); 
insert into orders (order_detail, person_id) values ('detail_5858', @person_id); 
insert into persons (person_name) values ('name_32601'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_24754', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24651', @person_id); 
insert into orders (order_detail, person_id) values ('detail_25088', @person_id); 
insert into orders (order_detail, person_id) values ('detail_29443', @person_id); 
insert into orders (order_detail, person_id) values ('detail_27244', @person_id); 
insert into persons (person_name) values ('name_25171'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19420', @person_id); 
insert into orders (order_detail, person_id) values ('detail_29701', @person_id); 
insert into orders (order_detail, person_id) values ('detail_31601', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26944', @person_id); 
insert into persons (person_name) values ('name_902'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_530', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28573', @person_id); 
insert into persons (person_name) values ('name_23364'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_20818', @person_id); 
insert into persons (person_name) values ('name_31925'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_1853', @person_id); 
insert into orders (order_detail, person_id) values ('detail_19982', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12605', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18177', @person_id); 
insert into orders (order_detail, person_id) values ('detail_17800', @person_id); 
insert into persons (person_name) values ('name_9190'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_27598', @person_id); 
insert into orders (order_detail, person_id) values ('detail_13232', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4983', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4691', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14572', @person_id); 
insert into persons (person_name) values ('name_7928'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_24024', @person_id); 
insert into persons (person_name) values ('name_6048'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_18182', @person_id); 
insert into orders (order_detail, person_id) values ('detail_3417', @person_id); 
insert into persons (person_name) values ('name_21428'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_2720', @person_id); 
insert into persons (person_name) values ('name_13231'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_20995', @person_id); 
insert into orders (order_detail, person_id) values ('detail_19517', @person_id); 
insert into orders (order_detail, person_id) values ('detail_31082', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16416', @person_id); 
insert into persons (person_name) values ('name_8343'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19999', @person_id); 
insert into orders (order_detail, person_id) values ('detail_23157', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24987', @person_id); 
insert into persons (person_name) values ('name_3476'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_6025', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24954', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16200', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4944', @person_id); 
insert into persons (person_name) values ('name_1357'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_12164', @person_id); 
insert into orders (order_detail, person_id) values ('detail_5691', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12475', @person_id); 
insert into orders (order_detail, person_id) values ('detail_23426', @person_id); 
insert into persons (person_name) values ('name_25144'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_22974', @person_id); 
insert into persons (person_name) values ('name_2222'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_23570', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11453', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11821', @person_id); 
insert into persons (person_name) values ('name_11238'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_12184', @person_id); 
insert into persons (person_name) values ('name_10011'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_29183', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14212', @person_id); 
insert into persons (person_name) values ('name_28350'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_3792', @person_id); 
insert into persons (person_name) values ('name_7489'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_17533', @person_id); 
insert into persons (person_name) values ('name_7268'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_8028', @person_id); 
insert into orders (order_detail, person_id) values ('detail_29954', @person_id); 
insert into orders (order_detail, person_id) values ('detail_25714', @person_id); 
insert into orders (order_detail, person_id) values ('detail_3856', @person_id); 
insert into persons (person_name) values ('name_28434'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_10001', @person_id); 
insert into orders (order_detail, person_id) values ('detail_23749', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8486', @person_id); 
insert into persons (person_name) values ('name_26025'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_26309', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18011', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14069', @person_id); 
insert into persons (person_name) values ('name_6149'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_6367', @person_id); 
insert into orders (order_detail, person_id) values ('detail_30309', @person_id); 
insert into orders (order_detail, person_id) values ('detail_2140', @person_id); 
insert into orders (order_detail, person_id) values ('detail_21427', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16196', @person_id); 
insert into persons (person_name) values ('name_15521'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_7548', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20954', @person_id); 
insert into persons (person_name) values ('name_17469'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_9706', @person_id); 
insert into orders (order_detail, person_id) values ('detail_10596', @person_id); 
insert into orders (order_detail, person_id) values ('detail_393', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20794', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16038', @person_id); 
insert into persons (person_name) values ('name_5318'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_2860', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12890', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26455', @person_id); 
insert into orders (order_detail, person_id) values ('detail_16364', @person_id); 
insert into persons (person_name) values ('name_11284'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_5203', @person_id); 
insert into orders (order_detail, person_id) values ('detail_2544', @person_id); 
insert into persons (person_name) values ('name_30749'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_16633', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12612', @person_id); 
insert into persons (person_name) values ('name_7335'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_9825', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20774', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14587', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4701', @person_id); 
insert into orders (order_detail, person_id) values ('detail_9308', @person_id); 
insert into persons (person_name) values ('name_10416'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_23857', @person_id); 
insert into persons (person_name) values ('name_29726'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_27802', @person_id); 
insert into orders (order_detail, person_id) values ('detail_10733', @person_id); 
insert into orders (order_detail, person_id) values ('detail_7272', @person_id); 
insert into orders (order_detail, person_id) values ('detail_9570', @person_id); 
insert into persons (person_name) values ('name_17805'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_21168', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8855', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28444', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20090', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18791', @person_id); 
insert into persons (person_name) values ('name_2547'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_17179', @person_id); 
insert into persons (person_name) values ('name_8935'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_6637', @person_id); 
insert into persons (person_name) values ('name_13676'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_32463', @person_id); 
insert into persons (person_name) values ('name_25291'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_6221', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28140', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15511', @person_id); 
insert into orders (order_detail, person_id) values ('detail_287', @person_id); 
insert into orders (order_detail, person_id) values ('detail_17073', @person_id); 
insert into persons (person_name) values ('name_9354'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_605', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24361', @person_id); 
insert into orders (order_detail, person_id) values ('detail_8519', @person_id); 
insert into persons (person_name) values ('name_16437'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_29012', @person_id); 
insert into orders (order_detail, person_id) values ('detail_17854', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18034', @person_id); 
insert into persons (person_name) values ('name_8006'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_20679', @person_id); 
insert into persons (person_name) values ('name_22993'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19425', @person_id); 
insert into orders (order_detail, person_id) values ('detail_23988', @person_id); 
insert into orders (order_detail, person_id) values ('detail_24970', @person_id); 
insert into orders (order_detail, person_id) values ('detail_27348', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14651', @person_id); 
insert into persons (person_name) values ('name_29421'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_18137', @person_id); 
insert into orders (order_detail, person_id) values ('detail_27603', @person_id); 
insert into persons (person_name) values ('name_32417'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_6112', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12576', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11481', @person_id); 
insert into persons (person_name) values ('name_980'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_25434', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18407', @person_id); 
insert into orders (order_detail, person_id) values ('detail_7522', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12751', @person_id); 
insert into persons (person_name) values ('name_6255'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_17312', @person_id); 
insert into orders (order_detail, person_id) values ('detail_22281', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12015', @person_id); 
insert into orders (order_detail, person_id) values ('detail_20664', @person_id); 
insert into persons (person_name) values ('name_6997'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_2577', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4530', @person_id); 
insert into persons (person_name) values ('name_24147'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_19680', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11897', @person_id); 
insert into persons (person_name) values ('name_8772'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_9716', @person_id); 
insert into persons (person_name) values ('name_18069'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_29889', @person_id); 
insert into orders (order_detail, person_id) values ('detail_25160', @person_id); 
insert into persons (person_name) values ('name_2320'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_11165', @person_id); 
insert into orders (order_detail, person_id) values ('detail_30099', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14163', @person_id); 
insert into orders (order_detail, person_id) values ('detail_27281', @person_id); 
insert into persons (person_name) values ('name_29326'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_28584', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15207', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26583', @person_id); 
insert into persons (person_name) values ('name_30946'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_27862', @person_id); 
insert into orders (order_detail, person_id) values ('detail_800', @person_id); 
insert into persons (person_name) values ('name_19710'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_14554', @person_id); 
insert into orders (order_detail, person_id) values ('detail_1994', @person_id); 
insert into orders (order_detail, person_id) values ('detail_555', @person_id); 
insert into orders (order_detail, person_id) values ('detail_3025', @person_id); 
insert into persons (person_name) values ('name_79'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_30264', @person_id); 
insert into orders (order_detail, person_id) values ('detail_2306', @person_id); 
insert into orders (order_detail, person_id) values ('detail_4516', @person_id); 
insert into orders (order_detail, person_id) values ('detail_18421', @person_id); 
insert into orders (order_detail, person_id) values ('detail_12636', @person_id); 
insert into persons (person_name) values ('name_7497'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_14039', @person_id); 
insert into orders (order_detail, person_id) values ('detail_6349', @person_id); 
insert into persons (person_name) values ('name_15369'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_4476', @person_id); 
insert into orders (order_detail, person_id) values ('detail_31770', @person_id); 
insert into orders (order_detail, person_id) values ('detail_17207', @person_id); 
insert into orders (order_detail, person_id) values ('detail_3471', @person_id); 
insert into orders (order_detail, person_id) values ('detail_14976', @person_id); 
insert into persons (person_name) values ('name_20594'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_32743', @person_id); 
insert into orders (order_detail, person_id) values ('detail_6200', @person_id); 
insert into persons (person_name) values ('name_11341'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_1620', @person_id); 
insert into orders (order_detail, person_id) values ('detail_32198', @person_id); 
insert into orders (order_detail, person_id) values ('detail_22734', @person_id); 
insert into persons (person_name) values ('name_20309'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_30733', @person_id); 
insert into orders (order_detail, person_id) values ('detail_22095', @person_id); 
insert into persons (person_name) values ('name_1778'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_14265', @person_id); 
insert into orders (order_detail, person_id) values ('detail_26342', @person_id); 
insert into orders (order_detail, person_id) values ('detail_11953', @person_id); 
insert into persons (person_name) values ('name_8552'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_27712', @person_id); 
insert into persons (person_name) values ('name_3049'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_1816', @person_id); 
insert into persons (person_name) values ('name_22748'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_1534', @person_id); 
insert into persons (person_name) values ('name_8962'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_24449', @person_id); 
insert into orders (order_detail, person_id) values ('detail_15746', @person_id); 
insert into orders (order_detail, person_id) values ('detail_9502', @person_id); 
insert into persons (person_name) values ('name_1169'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_20432', @person_id); 
insert into persons (person_name) values ('name_8632'); 
select last_insert_id() into @person_id; 
insert into orders (order_detail, person_id) values ('detail_16745', @person_id); 
insert into orders (order_detail, person_id) values ('detail_5025', @person_id); 
insert into orders (order_detail, person_id) values ('detail_23148', @person_id); 
insert into orders (order_detail, person_id) values ('detail_28991', @person_id); 
insert into orders (order_detail, person_id) values ('detail_1576', @person_id); 
